config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#home'

  get 'sessions/new'
  get '/login',      to: "sessions#new"
  post '/login',     to: "sessions#create"
  delete '/logout',  to: "sessions#destroy"

  resources :users
  get 'users/home'

  resources :events
  get 'events/new'
  get 'events/create'
  get 'events', to:"events#index"

  post 'events/:id', to: "events#subscribe"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User" ,foreign_key: "user_id"
    has_and_belongs_to_many :attendees , class_name: "User"

    validates :description, presence: true
    validates :date, presence: true
    validates :place, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events , class_name: "Event"
  has_and_belongs_to_many  :attended_events, class_name: "Event"

  attr_accessor :remember_token

  validates :name, presence: true,
                   uniqueness: { case_sensitive: false },
                   format: { with: /\A[a-zA-Z0-9_]*\z/ }
                   #RegExp du format Username

  EMAIL = /\A([\w\!\#\z\%\&\'\*\+\-\/\=\?\\A\`{\|\}\~]+\.)*[\w\+-]+@((((([a-z0-9]{1}[a-z0-9\-]{0,62}[a-z0-9]{1})|[a-z])\.)+[a-z]{2,6})|(\d{1,3}\.){3}\d{1,3}(\:\d{1,5})?)\z/i

  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    format: { with: EMAIL }
                    #RegExp du format Email

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
     self.remember_token = User.new_token
     update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def new
      if logged_in?
          @event= Event.new
      else
          redirect_to root_url
          flash[:danger] = "Veuillez vous connecter pour créer un nouvel événement."
      end
    end

    def create
    	@event = Event.new(event_params)
    	@event.creator = current_user
    	if @event.save
        flash[:success] = "Votre événement a bien été créé !"
        #Si la création du nouvel évent est bien réalisée, alors on fait afficher l'event créé via la fonction SHOW
        redirect_to @event
    	else
        render 'new'
        p "Une erreur existe, veuillez recommencer."
    	end
    end

    def show
      @event = Event.find(params[:id])

    end



    def index
      @events = Event.all
    end

    def edit
      @event = Event.find(params[:id])
      #Condition pour éviter l'édition d'événements dont on n'est pas le creator.
      if @event.creator.id != current_user.id
        flash[:danger] = 'Accès refusé ! '
        redirect_to root_path
      end
    end

    def update
      @event = Event.find(params[:id])
      if @event.update(event_params)
        #Si l'update est bien réalisée (true), alors on redirige vers la page de l'event.
        redirect_to @event
      else
        render 'edit'
      end
    end

    def destroy
      @event = Event.find(params[:id])
      #Condition pour éviter l'édition d'événements dont on n'est pas le creator.
      if @event.creator.id != current_user.id
        flash[:danger] = 'Accès refusé ! '
        redirect_to root_path
      else
        @event.destroy
        redirect_to events_path
        #On redirige vers l'index
      end
    end

    def subscribe
      @event = Event.find(params[:id])
      #COndition pour éviter de s'inscrire plusieurs fois
      if @event.attendees.include? current_user
          redirect_to @event
          flash[:danger] = "Vous êtes déjà inscrits"
      else
          @event.attendees << current_user
          flash[:success] = "Vous êtes inscrits"
          redirect_to @event
      end
    end


    private
  	def event_params
      params.require(:event).permit(:title, :description, :date, :place)
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      remember user
      redirect_to user
    else
      flash.now[:danger] = 'Mauvaise combinaison email/mot de passe'
      render 'new'
    end
  end

  def index
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home
  end

  def new
    @user= User.new
  end

  def create
    @user = User.new(user_params)
    if  @user.save
      log_in @user
      flash[:success] = "Bienvenue, Vous êtes bien inscrits." #Permet d'afficher une pop-up de confirmation de l'inscription.
      redirect_to @user  #Si la création du nouveau profil est bien réalisée, alors on fait afficher le profil crée via la fonction SHOW
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end


  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      flash[:danger] = 'Accès refusé !'
      redirect_to root_path
    end
  end

  def update
        @user = User.find(params[:id])
        if @user.update(user_params)
          #Si l'update est bien réalisée (true), alors on redirige vers la page du profil.
          redirect_to @user
        else
          render 'edit'
        end
  end

  def destroy
    @user = User.find(params[:id])
    #ON met une condition pour empëcher la suppression des comptes des autres.
    if @user.id = current_user.id
        @user.destroy
        redirect_to users_path
        #On redirige vers l'index
    else
        flash[:danger] = "Refusé ! C'est pô très gentil de vouloir faire ça !"
        redirect_to root_path
    end
  end



  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
    def remember(user)
      user.remember
      cookies.permanent.signed[:user_id] = user.id
      cookies.permanent[:remember_token] = user.remember_token
    end

  def current_user
    # Version sessions    @current_user ||= User.find_by(id: session[:user_id])

    # Returns the user corresponding to the remember token cookie.
      if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: user_id)
      elsif (user_id = cookies.signed[:user_id])
        user = User.find_by(id: user_id)
        if user && user.authenticated?(cookies[:remember_token])
          log_in user
          @current_user = user
        end
      end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/events/_form_event.html.erb
<%= form_for(@event) do |f| %>
  <%= render 'shared/error_messages_event', object: @event %>

  <%= f.label :"Nom de l'évenement" %>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.label :"Description de l'évenement" %>
  <%= f.text_field :description, class: 'form-control' %>

  <%= f.label :"Lieu de l'évenement" %>
  <%= f.text_field :place, class: 'form-control' %>

  <%= f.label :date %>
  <%= f.date_field :date, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/events/edit.html.erb
<% provide(:button_text, "Mettre à jour l'événement") %>

<h3>Editer l'événement</h3>

<div class="col-md-6 col-md-offset-3">
  <%= render 'form_event' %>
</div>
<br>
<div class="col-md-6 col-md-offset-3">
<h4>Effacer l'événement</h4><%= link_to 'Cliquer ici pour effacer cet événement', @event, method: :delete %>
<br><br>
<%= link_to 'Retour', event_path %>
</div>

app/views/events/index.html.erb
<h3>
  Liste des événements :
</h3>
<h4>Evenements à venir:</h4>
<table>
  <tr>
    <th>ID de l'evenement</th>
    <th>Nom de l'événement</th>
    <th>Date</th>
    <td>Lieu</td>
    <th>Createur</th>
  </tr>
  <br>
  <% @events.each do |event| %>
   <% if event.date >= Date.today %>
    <tr>
      <td><%= event.id %></td>
      <td><%= event.title %> </td>
      <td><%= event.date %></td>
      <td><%= event.place %></td>
      <td><%= event.creator.name %> </td>
      <td><%= link_to " Voir l'événement", event_path(event) %></td>
    </tr>
    <% end%>
  <% end %>
</table>
<br><br>
<h4>Evenements passés :</h4>
<table>
  <tr>
    <th>ID de l'evenement</th>
    <th>Nom de l'événement</th>
    <th>Date</th>
    <td>Lieu</td>
    <th>Createur</th>
  </tr>
  <br>
  <% @events.each do |event| %>
   <% if event.date < Date.today %>
    <tr>
      <td><%= event.id %></td>
      <td><%= event.title %> </td>
      <td><%= event.date %></td>
      <td><%= event.place %></td>
      <td><%= event.creator.name %> </td>
      <td><%= link_to " Voir l'événement", event_path(event) %></td>
    </tr>
    <% end%>
  <% end %>
</table>
<br><br>
<%= link_to "Créer un nouvel événement", '/events/new' %>

app/views/events/new.html.erb
<% provide(:button_text, "Créer l'événement") %>

<h2>Création d'un nouvel événement</h2>
<p>Bonjour, pour créer un évenement,
  <br>veuillez remplir les champs suivants :
</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form_event' %>
  </div>
</div>
<br>
<p> <a href="/">Retourner à l'accueil</a> </p>

app/views/events/show.html.erb
<h2>L'évenement créé : <%= @event.title %></h2>
<br><br>
<p>Un événement créé par <%= @event.creator.name %>
<p>Description de l'événement: <%= @event.description %>
  <br>
<p>Le lieu: <%= @event.place %>
<br>Le jour: <%= @event.date %></p>
</p>
<br>
<p> <%= link_to "Rectifier les inforamtions sur l'événement", edit_event_path%></p>
<p> <%= link_to 'Supprimer cet évenement', event_path(@event), method: :delete ,
              data: { confirm: 'Etes vous sur ?' }%></p>
<br>

<%= button_to "S'inscrire à l'événement", {:controller => :events,
      :action => 'subscribe' }, :class => 'btn btn-primary'%>
<br><br>
<h3>
  Liste des personnes inscrites à l'événement :
</h3>
<table>
  <tr>
    <th>Pseudo</th>
    <th>Profil</th>
  </tr>
  <br>
  <% @event.attendees.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to "Voir le profil", user_path(user)%></td>
  </tr>
  <% end %>
</table>
<br><br>



<p> <a href="/">Retourner à l'accueil</a> </p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil", '/' %></li>
        <% if logged_in? %>
            <li><%= link_to "Mon profil", current_user %></li>
            <li><%= link_to "Liste des événements", events_path %> </li>
            <li class="divider"></li>
            <li><%= link_to "Déconnexion", logout_path, method: :delete %> </li>

        <% else %>
            <li><%= link_to "S'inscrire", '/users/new' %></li>
            <li><%= link_to "Se connecter", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteLike</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="pageprincipale">
      <!-- COde pour afficher un message pop-up de bienvenue après l'inscription -->
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
<!-- Debug mode-->
      <%= debug(params) if Rails.env.development? %>

    </div>
  </body>
</html>

app/views/shared/_error_messages_event.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@event.errors.count, "error") %>.
    </div>
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_user.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages_user', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<% provide(:button_text, "Mettre à jour") %>

<h3>Editer le profil du user</h3>

<div class="col-md-6 col-md-offset-3">
  <%= render 'form' %>
</div>
<br>
<h4>Effacer le profil</h4>
<%= link_to 'Cliquer ici pour effacer ce profil', @user, method: :delete %>
<br><br>
<%= link_to 'Retour', user_path %>

app/views/users/home.html.erb
<h1>Bienvenue</h1>
<p>Vous pouvez dès à present, créer un événement ou bien participer à des événements existants ! </p>
<%= link_to "Créer un compte", '/users/new', class: "btn btn-lg btn-primary" %>
<br><br>
<%= link_to "Créer un événement", '/events/new', class: "btn btn-lg btn-primary" %>

app/views/users/new.html.erb
<% provide(:button_text, "S'inscrire") %>

<h2>Inscription</h2>
<p>Bonjour, pour vous inscrire,
  <br>veuillez remplir les champs suivants :
</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>
<br>
<p> <a href="/">Retourner à l'accueil</a> </p>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>
<br><br>
Voici les informations entrées :
<br><br>
<p>Prénom: <%= @user.name %>
<br>Email: <%= @user.email %></p>
</p>
<br>
<p> <%= link_to "Rectifier les inforamtions", edit_user_path%></p>
<p> <%= link_to 'Supprimer ce profil', user_path(@user), method: :delete ,
              data: { confirm: 'Etes vous sur ?' }%></p>
<br><br>

<h3>
  Liste des événements à venir créés par <%= @user.name %> :
</h3>

<table>
  <tr>
    <th>ID de l'evenement</th>
    <th>Nom de l'événement</th>
    <th>Date</th>
    <th>Lieu</th>
  </tr>
  <br>
  <!--On affiche chaque événement ajoutés dans la table created_events  -->
  <% @user.created_events.each do |event| %>
    <!-- On récupère uniquement les événements à venir-->
     <% if event.date >= Date.today %>
        <tr>
          <td><%= event.id %></td>
          <td><%= event.title %> </td>
          <td><%= event.date %></td>
          <td><%= event.place %></td>
          <td><%= link_to "Voir l'événement", event_path(event) %></td>
        </tr>
     <% end%>
  <% end %>
</table>
<br><br>


<%= link_to "Créer un nouvel événement", '/events/new' %>



<h3>
  Liste des événements auxquels <%= @user.name %> participe prochainement :
</h3>

<table>
  <tr>
    <th>ID de l'evenement</th>
    <th>Nom de l'événement</th>
    <th>Date</th>
    <th>Lieu</th>
  </tr>
  <br>
  <!--On affiche chaque événement ajoutés dans la table attended_events  -->
  <% @user.attended_events.each do |event| %>
       <!-- On récupère uniquement les événements à venir-->
       <% if event.date >= Date.today %>
         <tr>
            <td><%= event.id %></td>
            <td><%= event.title %> </td>
            <td><%= event.date %></td>
            <td><%= event.place %></td>
            <td><%= link_to "Voir l'événement", event_path(event) %></td>
          </tr>
        <% end %>
  <% end %>
</table>

<br><br>

<h3>
  Liste des événements auxquels <%= @user.name %> a participé :
</h3>

<table>
  <tr>
    <th>ID de l'evenement</th>
    <th>Nom de l'événement</th>
    <th>Date</th>
    <th>Lieu</th>
  </tr>
  <br>
  <!--On affiche chaque événement ajoutés dans la table attended_events  -->
  <% @user.attended_events.each do |event| %>
  <!-- On récupère uniquement les événements à venir-->

    <!-- On récupère uniquement les événements passés-->
     <% if event.date < Date.today %>
       <tr>
          <td><%= event.id %></td>
          <td><%= event.title %> </td>
          <td><%= event.date %></td>
          <td><%= event.place %></td>
          <td><%= link_to "Voir l'événement", event_path(event) %></td>
        </tr>
      <% end %>
  <% end %>
</table>
<br><br>


<br><br>
<p> <a href="/">Retourner à l'accueil</a> </p>